### ISSUE TITLE
1.0.0 compatibility

### ISSUE THREAD

**Issue by LinusU** [dustin-H/multer-storage-pkgcloud#1]
The requirements for storage engines have slightly changed.
- [x] Rename `handleFile` to `_handleFile`
- [x] Implement `_removeFile`

**Comment by LinusU** [comment]
Documentation: https://github.com/expressjs/multer/blob/master/StorageEngine.md

**Comment by dustin-H** [comment]
Nice to hear about 1.0.0 release. And thank you for inform me about the release changes! Will going to fix this tomorrow!

**Comment by dustin-H** [comment]
Done! :) :beers:

**Comment by LinusU** [comment]
Nice :+1:

**Comment by dustin-H** [comment]
b18fd52570d2fa730ec3271f0851c3f47678111b

**Comment by LinusU** [comment]
:ok_hand:
